# Generated by Django 5.0.6 on 2024-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название книги')),
                ('date', models.DateField(verbose_name='дата создания книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('pages', models.IntegerField(verbose_name='число страниц')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('writed_books', models.ManyToManyField(to='books.book', verbose_name='')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название жанра')),
                ('description', models.TextField(verbose_name='Описание Жанра')),
                ('date', models.DateField(verbose_name='дата создания жанра')),
                ('authors', models.ManyToManyField(to='books.author', verbose_name='')),
                ('books', models.ManyToManyField(to='books.book', verbose_name='')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
    ]
