# Generated by Django 5.0.6 on 2024-06-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='commentaries',
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name=''),
            preserve_default=False,
        ),
    ]
