# Generated by Django 5.0.6 on 2024-06-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_writed_books_alter_genre_authors'),
        ('books', '0004_alter_comment_options_remove_book_commentaries_and_more'),
    ]

    operations = [
    ]
