# Generated by Django 5.0.6 on 2024-06-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_merge_20240627_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.genre', verbose_name=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='author',
            name='writed_books',
        ),
        migrations.AddField(
            model_name='author',
            name='writed_books',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name=''),
            preserve_default=False,
        ),
    ]
