# Generated by Django 5.0.6 on 2024-06-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_genre_authors_remove_genre_books_book_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='writed_books',
        ),
        migrations.AddField(
            model_name='author',
            name='date',
            field=models.DateField(default='2015-12-17', verbose_name='дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='books.author', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания книги'),
        ),
    ]
